secretGenerator:
  - name: db-password
    literals:
      - password=supersecurepasswordhere
  - name: django
    literals:
      - secret=secretkey123-example

resources:
  - postgres.yaml
  - django.yaml